### PR TITLE
add a 'gravity' slider.

### PR DESCRIPTION
**Pull request by skal65535**
Effect of gravity is just to force particles to interact more at the bottom where they 'precipitate'.

### CODE REVIEW

**Comment by skal65535** [comment]
forgot to mention that all particles have the same (unit) mass for now.

**Review by ker2x — COMMENTED** [review]
tested in cpp. not really sure about how interesting it is but it's basically free in cpu, so, sure, why not.

**Comment by ker2x** [comment]
it might be interesting to have the particle attracted to the center instead of downward, if the world is unbounded they just vanish out of screen

**Comment by skal65535** [comment]
the html version has a 'wall repel' feature to prevent this. Is it present in the cpp version?

**Comment by ker2x** [comment]
> the html version has a 'wall repel' feature to prevent this. Is it present in the cpp version?

no, i suppose i'll add it

**Pull request merged**
